#language: python
#python:
#  - '3.6'
#matrix:
#  include:
#    - python: '3.7'
#      dist: xenial
#      sudo: true
#install:
#  - 'pip install pipenv'
#  - 'pipenv sync'
#script: 'pipenv run python -m pytest'

language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7-dev"

# command to install dependencies
install: "make"

# command to run tests
script:
    - make test